### ISSUE TITLE
Ask.Fedora referring to old Askbot software

### ISSUE THREAD

**Issue by heis2201** [fedora-infra/apps.fp.o#70]
Information on Ask.fp.o is still fior the old askbot software. This would have to updated to reflect Discourse hosting...

```
 source_url: https://github.com/askbot/askbot-devel
            bugs_url:   https://github.com/askbot/askbot-devel/issues/
            docs_url:   http://askbot.org/doc/index.html
            sops:
                - https://infrastructure.fedoraproject.org/infra/docs/askbot.rst
```
